name: Publish to Chrome store

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Publish to Chrome store
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: 16
    - name: Build
      run: |
        npm ci
        npm run pub-ci
    - name: Install the webstore-upload-cli
      run: |
        npm install chrome-webstore-upload-cli
        pwd
    - name: Upload 
      run: |
        ./node_modules/chrome-webstore-upload-cli/cli.js upload --source build.zip --extension-id ckncjmaednfephhbpeookmknhmjjodcd --client-id ${{ secrets.CLIENT_ID }} --client-secret ${{ secrets.CLIENT_SECRET }} --refresh-token ${{ secrets.REFRESH_TOKEN }}
    - name: Publish 
      run: |
        ./node_modules/chrome-webstore-upload-cli/cli.js publish --extension-id ckncjmaednfephhbpeookmknhmjjodcd --client-id ${{ secrets.CLIENT_ID }} --client-secret ${{ secrets.CLIENT_SECRET }} --refresh-token ${{ secrets.REFRESH_TOKEN }}
